### ISSUE TITLE
Add subdirectory example to Cloud Files quickstart

### ISSUE THREAD

**Issue by carolynvs** [rackerlabs/docs-quickstart#110]
It's been asked enough that I think this FAQ, "How to make subdirectories in Cloud Files" belongs in the the [quickstart](https://developer.rackspace.com/docs/cloud-files/quickstart/). I am sure it is spelled out elsewhere, but is missed by developers coming in through the quickstart guide.

I have the code for .NET since I just answered this question. 😄 If you agree it belongs in the quickstart, I'll send a PR for it and curl.

**Comment by cyrichardson** [comment]
Yay, @carolynvs!

**Comment by carolynvs** [comment]
I'll take that as a yes and send a PR tomorrow. 😄
