### ISSUE TITLE
Node.js CDN quickstart refers to missing code

### ISSUE THREAD

**Issue by EvanK** [rackerlabs/docs-quickstart#12]
All Node.js code samples in the [CDN Quickstart](https://developer.rackspace.com/docs/cdn/getting-started/) refer to objects underneath `pkgcloud.cdn`, however there _is_ no `cdn` within current versions of pkgcloud.

Upon cursory examination of [the pkgcloud github repo](https://github.com/pkgcloud/pkgcloud), it looks like it was thought the same as Cloud Files CDN and removed?

**Comment by smashwilson** [comment]
I do see [a `dns` directory within pkgcloud](https://github.com/pkgcloud/pkgcloud/tree/master/lib/pkgcloud/rackspace/dns) under the Rackspace provider, but I'm not a pkgcloud expert. Maybe it isn't being exported correctly?

@kenperkins Do you have any insights about this? Does the quickstart guide need to be updated somehow?

**Comment by kenperkins** [comment]
Looks like we need to merge and publish. Let me try and address that this week.

**Comment by steveortiz** [comment]
@EvanK: what version of pkgcloud are you using? Thanks!

**Comment by EvanK** [comment]
On 1.1.0, we get:

```
Error: rackspace does not expose a cdn service
    at Object.pkgcloud.(anonymous function).createClient (~/cdntest/node_modules/pkgcloud/lib/pkgcloud.js:94:13)
```

And on 1.2.0, we get:

```
[Error: Unable to identify endpoint url]
```

If you check their github, they've actually _removed_ all reference to a `cdn` service, as well

**Comment by EvanK** [comment]
On 1.1.0, we get:

```
Error: rackspace does not expose a cdn service
    at Object.pkgcloud.(anonymous function).createClient (~/cdntest/node_modules/pkgcloud/lib/pkgcloud.js:94:13)
```

And on 1.2.0, we get:

```
[Error: Unable to identify endpoint url]
```

If you check their github, they've actually _removed_ all reference to a `cdn` service, as well

**Comment by kenperkins** [comment]
@EvanK you can find it here: https://github.com/pkgcloud/pkgcloud/tree/v1.2.0-alpha.0

**Comment by EvanK** [comment]
Using `1.2.0-alpha.0`, we get the same `Unable to identify endpoint url` error upon calling `client.getFlavors` or `client.getServices`.

Curiously, we _are_ able to create a client on which to call the above methods ¯\\\_(ツ)_/¯

**Comment by kenperkins** [comment]
What `region` are you setting for the compute provider?

**Comment by redappleorigin** [comment]
I ended up using DFW. That made it work, but the docs don't say that I need this. I thought that the region was optional.

**Comment by kenperkins** [comment]
Region has never been optional; is there a documentation clarification we should make?

**Comment by redappleorigin** [comment]
https://developer.rackspace.com/docs/cdn/getting-started/?lang=node.js on the example when creating the client, including region would be nice.

**Comment by rgbkrk** [comment]
Noticing today that on Cloud Servers e.g., it's currently showing PHP code when node is selected:

https://developer.rackspace.com/docs/cloud-servers/getting-started/#authentication

Other languages render correctly.

**Comment by ktbartholomew** [comment]
Uh oh, I thought @rgbkrk's comment was an issue unto itself.

**Comment by rgbkrk** [comment]
Sorry, wasn't sure if it was related. I was in and out here. This *should have been* a separate issue.

`/me whistles`
