### ISSUE TITLE
Add RPC v13 product to developer.rackspace.com landing page

### ISSUE THREAD

**Issue by darrenchan** [rackerlabs/docs-quickstart#120]
Add RPC v13 product to the landing page. Related to https://github.com/rackerlabs/nexus-control/issues/566

For more information, see http://rackerlabs.github.io/docs-rackspace/tools/publishing.html

Ccing: @klevenstein @robb-romans @erikmwilson @kallimachos @meker12

**Comment by meker12** [comment]
Done: https://developer.rackspace.com/docs/#docs-private-cloud
