### ISSUE TITLE
Optimize CDN Images

### ISSUE THREAD

**Issue by mandabrainvire** [rackerlabs/docs-quickstart#143]
Hello there,

We have a CDN with rackspace for our magento site. 
While optimizing site speed, there is a huge collection showing up as not optimized images from CDN of rackspace.
Is there any way I can optimize my CDN images?
Please help ASAP.

Manda

**Comment by nimbinatus** [comment]
Hi @mandabrainvire,
Unfortunately, this repo is not the best way to reach a support team to help you. Please open up a support ticket on your dashboard or call support at 1-800-961-4454.
