### ISSUE TITLE
Cloud Files Quick Start link problem

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-quickstart#23]
At http://staging.developer.rackspace.com/docs/cloud-files/getting-started/#get-object-via-cdn-url, there is a link given beside Pre-requisite that doesn't appear to be working.

**Comment by meker12** [comment]
So this is odd -- In the [Cloud Files Quickstart](https://github.com/rackerlabs/docs-quickstart/blob/master/cloud-files/quickstart/index.rst) source file, the link above is working. It links to a section "CDN-enable container".  The content also has additional headers and formatting that is not included in the production copy. The source page is clearer and more helpful.

[Source file](https://github.com/rackerlabs/docs-quickstart/blob/master/cloud-files/quickstart/index.rst)

![files-source-repo-index-page](https://cloud.githubusercontent.com/assets/6391769/15377295/4dce5a8c-1d20-11e6-8d1e-f52b20f959d2.png)

[Production page](https://developer.rackspace.com/docs/cloud-files/quickstart/?lang=go)

![files-production-content](https://cloud.githubusercontent.com/assets/6391769/15377297/53aae614-1d20-11e6-9a4a-a924d1f1108c.png)

**Comment by meker12** [comment]
@ktbartholomew  Can you take a look at this issue please.  I can't figure out why the content is not matching.  When I build locally, the Cloud Files page looks as expected.  But, when built by deconst, it doesn't match.

**Comment by ktbartholomew** [comment]
This issue seems to have resolved itself. The live page now has all headers that were previously missing.
