### ISSUE TITLE
Cloud Big Data Quick Start?

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-quickstart#25]
Links to https://www.developer.rackspace.com/docs/ show nothing available for Cloud Big Data.

**Comment by annegentle** [comment]
@cyrichardson this seems resolved, can you close? Thanks!

**Comment by cyrichardson** [comment]
@annegentle closing

**Comment by cyrichardson** [comment]
@annegentle It opens the getting started guide on docs.rackspace.com.
There is not a SDK quick start for CBD.
@annegentle Do you still think closing is appropriate, or should I reopen?

**Comment by annegentle** [comment]
Why is it not written? Do you know? (Honestly asking, I don't know context here.) Raj would like one written with the openstack sdk.

**Comment by jnoller** [comment]
@annegentle because the SDKs don't support CBD

**Comment by annegentle** [comment]
Er, sorry, I'm crossing Issues here, nevermind. :blush:

**Comment by annegentle** [comment]
I don't think there has to be a quickstart for a product that doesn't have SDK support. Let's keep this issue open though to make sure it's resolved through migrating the Getting Starteds.

**Comment by cyrichardson** [comment]
@annegentle OK - reopened.

**Comment by meker12** [comment]
Cloud Big Data doesn't have an SDK Quickstart.  However, it does have an [API Getting Started Guide](https://developer.rackspace.com/docs/cloud-big-data/v2/developer-guide/#getting-started).

Closing this issue.
