### ISSUE TITLE
Edits for main text on http://staging.developer.rackspace.com/docs/

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-quickstart#27]
This will be a list!

* Under all of the categories that list Quick Start, that label should be changed to Quickstart to match what the docs are actually called. 

* Under **Cloud Servers (Legacy)**, remove API from the link to the Developer Guide. This will make it consistent with the other links to the same type of document.

* Under **Networking Services**, edit the first sentence to be as follows: 
Cloud networking services are on-demand and scalable, and provide technology-agnostic network abstraction, load balancing, and DNS management. 

* Under **Storage Services**, edit the first sentence to be as follows:
With our storage services, you can get dependable and high-performing block storage, object storage, and backup solutions for Cloud Servers. 

* The label for Cloud CDN needs to change to Rackspace CDN. 

* Under **Database Services**, change "pre-configured, highly performant and available" to "preconfigured, high-performing, and available"

* The label Redistogo should be changed to Redis To Go. That is the name used in the Redis docs. 

* Under **Infrastructure & Developer Services**, in the third sentence, change Autoscale to Auto Scale, and change "in response to in increase" to "in response to an increase" 

* Change the label Autoscale to Rackspace Auto Scale. 

* For the SDKs & Tools, I'd change the last sentence as follows: 
Whether you are a Java, Go, .NET, Python, PHP, or JavaScript developer, or a polyglot, we speak your language.

**Comment by annegentle** [comment]
@kmsholcomb you can close this issue, thanks!

**Comment by kmsholcomb** [comment]
OK!
