### ISSUE TITLE
Incorrect link in cloud orchestration guide 

### ISSUE THREAD

**Issue by raj-patel** [rackerlabs/docs-quickstart#45]
In cloud orchestration dev guide, there is a link for getting latest templates https://github.com/rackspace-heat-templates. The link is incorrect and it should point to https://github.com/rackspace-orchestration-templates/

**Comment by meker12** [comment]
@raj-patel   Thanks for letting us know.  Moving this issue over to the 
Orchestration docs source repo. See https://github.com/rackerlabs/docs-cloud-orchestration/issues/25.
