### ISSUE TITLE
Add permalinks to the product API doc listing for direct linking

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-quickstart#47]
The Orchestration team would like to provide customer with a direct link to the Orchestration docs. 

Currently, they have these options:

Link to developer.rackspace.com, and then customer has to locate Orchestration which is near bottom.  Easiest thing is to do a search, but that's not very elegant. 

Request:

Add a permalink to the API and SDK doc list for each offering so that people could jump directly to a specific set of product information.

**Comment by ktbartholomew** [comment]
You mean a link like this? https://developer.rackspace.com/docs/#sdks

**Comment by meker12** [comment]
Hi Keith -- I think that we can fix this in the Quick Start source by just adding anchor refs to the H4s.  

That would let you use something like this to jump to Cloud Orchestration docs with this link:

https://developer.rackspace.com/docs/#cloud-orchestration

However, it would be nice to have the cool permalink icon so people knew there was a link there: 

![permalinks-on-landing-page](https://cloud.githubusercontent.com/assets/6391769/10981385/22651af8-83cd-11e5-999e-0f206b224e08.png)

**Comment by meker12** [comment]
@ktbartholomew    OK.  I see that I can add the permalink code.  However, it isn't supported by the docs-home.html template.  

Not sure how to add support for it -- looks like something needs to change in the assets.

**Comment by meker12** [comment]
OK.  I see that I can add the permalink code.  However, it isn't supported by the docs-page.html template, or maybe the docs-home.html template?

**Comment by ktbartholomew** [comment]
I don't think a visible anchor link icon adds much value to this page, but adding invisible anchor links to each "card" is as easy as adding a unique `id="something"` attribute to each card. The effect of doing this wouldn't be much different from what we have now, where you can already jump to each section.

**Comment by meker12** [comment]
See first issue.  **Product managers want to be able to give a user a direct anchor link to jump to set of product documentation** on the landing page--that begins with H4 header.   Can you accomplish that by just adding a names to the H4 headers.  

I tried that locally and built with deconst local client, but the jumps didn't work.

**Comment by ktbartholomew** [comment]
Adding an id attribute to the H4's would be the ideal way to solve this, then.

**Comment by meker12** [comment]
OK -- verifying the syntax for that:  

```
   <h4 id="orchestration-doc">Cloud Orchestration</h4>
                       </div>

```

Then the URL would be:  https://developer.rackspace.com/docs/#orchestration-doc

```

**Comment by ktbartholomew** [comment]
That's correct. For predictability, we should probably use the name of each repository for the id attributes, e.g: `id="docs-cloud-orchestration"`

**Comment by meker12** [comment]
OK.  Using the github repo name is a good idea.  

The other problem is that the availability of these IDs is secret -- people have to know they exist. 

Permalinks have the awesome capability of announcing their presence and users can also right-click to copy the link. 

Would it be that hard to add support for that?  I volunteer to update all the H4 to add the code if that's necessary.

**Comment by ktbartholomew** [comment]
I don't think visual anchor links are a good fit for this page. This page is intended as a portal to quickly scan and jump to various bits of documentation, not to keep portions of the page as a reference. The desire to have a "direct link" to their docs is symptomatic of a need for a coherent landing page that introduces the various pieces of documentation that are available available and explains what each should be used for.

A tiny card with six non-descriptive links doesn't seem like it can solve this problem without bending the UI pattern to do things it wasn't meant to do. With a dedicated orchestration docs landing page, we'd have a lot more flexibility to create something useful.

**Comment by meker12** [comment]
The Orchestration team actually asked for a Dedicated landing page for Orchestration docs, but we don't currently support that for individual products.  Something to discuss with Laura and team.

**Comment by ktbartholomew** [comment]
If they're ok with waiting a bit, I'd rather avoid adding a bunch of band-aids and wait until we can do it right, then. :smile:

**Comment by ktbartholomew** [comment]
"Band-aids" being visible anchor links. Invisible id attributes are fine.

**Comment by meker12** [comment]
Understood. Raised the issue with Laura and team. Thanks for your help.
