### ISSUE TITLE
Left navigation links in SDK don't work due to collapsed sections

### ISSUE THREAD

**Issue by carolynvs** [rackerlabs/docs-quickstart#54]
I'm looking at the compute api and want to dig into something from the left hand side, e.g. Network extension. When I click the link, it goes nowhere. If I figure out the right section in the main body to expand (e.g. api reference ), then some links work however the ones deeper down (mainly all the extensions) I can't get the link to work regardless of expanding things.

e.g. https://developer.rackspace.com/docs/cloud-servers/v2/developer-guide/#document-extensions/ext-network doesn't go where it should.

**Comment by meker12** [comment]
The links in the navigation are working now.
