### ISSUE TITLE
link "More information" sections to API doc at developer.rackspace.com

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-quickstart#59]
current links are to docs.rackspace.com, which then redirects to developer.rackspace.com

Also, since the content of every "More information" section is identical, edit /_common/moreinfo.rst and include it in each product-specific quickstart rather than maintaining multiple copies of the same text. This sets us up for easier maintenance as other linked-to doc moves.

**Comment by rose-coste** [comment]
I'm working on this today but don't have privileges to assign myself.

**Comment by meker12** [comment]
Updated link to how-to content. Other link already fixed.
