### ISSUE TITLE
coordinate Concepts sections with general glossary project

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-quickstart#62]
These product-specific Quickstarts introduce basic terms in Concepts sections. 
Some of the same terms are defined in the common glossary for API doc, under construction at https://github.com/rackerlabs/docs-common/blob/master/_common/glossary.txt. 
We need a plan for at least making sure these sources don't contradict each other. 

This is related to https://github.com/rackerlabs/docs-core-infra-user-guide/issues/393, asking for the same coordination with vocabulary introduced in userguides. 

@stephamon is very knowledgeable about the glossary project.

**Comment by meker12** [comment]
Stephanie consolidated concepts in glossary. Source available at https://github.com/rackerlabs/docs-rackspace/tree/master/doc/glossary
