### ISSUE TITLE
Docs titles under the Private Cloud card

### ISSUE THREAD

**Issue by darrenchan** [rackerlabs/docs-quickstart#70]
A couple of small changes under the Private Cloud card in https://developer.rackspace.com/docs/#docs-private-cloud:

* [ ] Change the "Other" heading to "Rackspace Private Cloud Powered by Red Hat"
* [ ] Rename the "Rackspace Private Cloud Powered by Red Hat" link to "Features and Architecture Guide"
* [ ] Create a "Managed VMWare Services" heading with the vCenter and vCloud links nested underneath
* [ ] Under "RACKSPACE PRIVATE CLOUD V11", add links to the Release Notes, Standalone Object Storage Guide, and Upgrade Guide  
* [ ] Under "RACKSPACE PRIVATE CLOUD V10", add links to the Release Notes and
Technical FAQ.

Thanks @ktbartholomew!

@kallimachos, FYI

**Comment by darrenchan** [comment]
@ktbartholomew any chance this can be actioned in the next day? Once items 1-3 are done, I can notify stakeholders of the changes.

Thanks for your help!

**Comment by ktbartholomew** [comment]
@darrenchan I've added this to our Waffle board ( https://waffle.io/rackerlabs/dxeng/cards/56d513394c057d1300551d6b) to make sure it's part of our current sprint. Adding individual links for all of those documents will make the one RPC card way too big; much larger than any of the other cards on that page. We'll need to split it up into 3 separate cards for RPC, VMWare, and vCenter:

### Rackspace Private Cloud

#### Rackspace Private Cloud v11

* Administrator Guide
* Technical FAQ
* Operations Guide
* Release Notes
* Standalone Object Storage Guide
* Upgrade Guide

#### Rackspace Private Cloud v10

* Administrator Guide
* Technical FAQ
* Operations Guide
* Release Notes

----------

### Managed VMWare Service

* vCenter Customer Handbook
* vCloud Customer Handbook – v1.0
* vCloud Customer Handbook – v1.5

----------

### Rackspace Private Cloud Powered by Red Hat

* Features and Architecture Guide

**Comment by darrenchan** [comment]
That makes sense. Thanks @ktbartholomew.
