### ISSUE TITLE
Add v12 section to the RPCO card

### ISSUE THREAD

**Issue by darrenchan** [rackerlabs/docs-quickstart#85]
Hi @ktbartholomew,

For RPCO v12.1 release on **25 April**:

- We need a v12 section added under the [Rackspace Private Cloud landing page](https://developer.rackspace.com/docs/), and docs published from the https://github.com/rackerlabs/docs-rpc/tree/v12 branch. We've added the content id in doc/_deconst.json.

- Rename "Rackspace Private Cloud" card to "Rackspace Private Cloud Powered by OpenStack". 

Let me know if you need any more information. Thanks!

CCing @kallimachos @RobinJoe @erikmwilson @klevenstein

**Comment by klevenstein** [comment]
also cc: @meker12

**Comment by meker12** [comment]
I can make these landing page updates @ktbartholomew.

**Comment by ktbartholomew** [comment]
Thanks @meker12! :bow:

**Comment by meker12** [comment]
@darrenchan  You can check the preview for these changes here: https://staging.developer.rackspace.com/build-bc27b8674b/docs/

Links won't work until content is published to production URL.

**Comment by darrenchan** [comment]
Fantastic, thanks @meker12 ! 👍
